export const ROUTE_PATHS = {
  root: '/',
  login: '/auth/login',
  otp: '/auth/otp',
  firstLoginSetup: '/auth/first-login/setup',
  resetPassword: '/auth/reset-password',
  dashboard: '/dashboard',
  kyc: '/kyc',
  ledger: '/ledger',
  transactionDetail: (ref: string) => `/ledger/${ref}`,
  transactionDetailPattern: '/ledger/:reference',
  profile: '/profile',
  transfer: '/payments/transfer',
  qrPayment: '/payments/qr',
  billPayment: '/payments/bills',
  tickets: '/support/tickets',
  ticketDetail: (ticketId: number) => `/support/tickets/${ticketId}`,
  ticketDetailPattern: '/support/tickets/:ticketId',
  notifications: '/notifications',
  staff: '/staff',
  staffUsers: '/staff/users',
  staffRegisterStaff: '/staff/users/register-staff',
  staffKyc: '/staff/kyc',
  staffAccounts: '/staff/accounts',
  staffLedger: '/staff/ledger',
  staffSupport: '/staff/support',
  staffTicketDetail: (ticketId: number | string) => `/staff/support/tickets/${ticketId}`,
  staffTicketDetailPattern: '/staff/support/tickets/:ticketId',
  staffRisk: '/staff/risk',
  staffReports: '/staff/reports',
  staffTellerRegisterCustomer: '/staff/teller/register',
  staffTellerDeposit: '/staff/teller/deposit',
  staffTellerWithdraw: '/staff/teller/withdraw',
  staffTellerAccountTransactions: '/staff/teller/account-transactions',
  staffTellerCustomerLookup: '/staff/teller/customers',
  staffTellerCustomerProfile: (userId: number | string) => `/staff/teller/customers/${userId}`,
  staffTellerCustomerProfilePattern: '/staff/teller/customers/:userId',
  forbidden: '/forbidden',
  notFound: '*',
} as const
