# SaFe-T Frontend Production Setup Script
# This script configures the frontend for production deployment

Write-Host "🚀 SaFe-T Production Setup" -ForegroundColor Green
Write-Host "================================" -ForegroundColor Green
Write-Host ""

# Check if we're in the frontend directory
if (!(Test-Path "package.json")) {
    Write-Host "❌ Error: Please run this script from the frontend directory" -ForegroundColor Red
    exit 1
}

Write-Host "📝 Creating production environment file..." -ForegroundColor Yellow

# Create .env.production file
$envContent = @"
# Production Environment Variables
# Auto-generated by setup-production.ps1

# Backend API URL (no trailing slash)
VITE_API_BASE_URL=https://api.safe-t-app.site

# Mock mode disabled for production
VITE_DEV_MOCK_MODE=false
"@

$envContent | Out-File -FilePath ".env.production" -Encoding UTF8
Write-Host "✅ Created .env.production" -ForegroundColor Green

# Also create .env for local development if it doesn't exist
if (!(Test-Path ".env")) {
    Write-Host "📝 Creating .env for local development..." -ForegroundColor Yellow
    $devEnvContent = @"
# Development Environment Variables

# Backend API URL (no trailing slash)
VITE_API_BASE_URL=http://localhost:8000

# Mock mode for testing without backend
VITE_DEV_MOCK_MODE=false
"@
    $devEnvContent | Out-File -FilePath ".env" -Encoding UTF8
    Write-Host "✅ Created .env" -ForegroundColor Green
}

Write-Host ""
Write-Host "🎯 Configuration Summary:" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host "Production API: https://api.safe-t-app.site" -ForegroundColor White
Write-Host "Local Dev API:  http://localhost:8000" -ForegroundColor White
Write-Host ""

Write-Host "📦 Next Steps:" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host "1. Build for Web (PWA):" -ForegroundColor White
Write-Host "   npm run build:prod" -ForegroundColor Yellow
Write-Host ""
Write-Host "2. Build for Mobile (Android):" -ForegroundColor White
Write-Host "   npm run build:mobile:prod" -ForegroundColor Yellow
Write-Host ""
Write-Host "3. Preview production build:" -ForegroundColor White
Write-Host "   npm run preview" -ForegroundColor Yellow
Write-Host ""
Write-Host "4. Deploy to hosting:" -ForegroundColor White
Write-Host "   Upload 'dist' folder to your web server" -ForegroundColor Yellow
Write-Host ""

Write-Host "✅ Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "📖 For detailed deployment instructions, see:" -ForegroundColor Cyan
Write-Host "   ../DEPLOYMENT.md" -ForegroundColor Yellow
Write-Host ""
