# Generated by Django 6.0.4 on 2026-04-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_first_login_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(blank=True, max_length=64)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_city", models.CharField(blank=True, max_length=120)),
                ("address_country", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="staff_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "staff_profiles",
                "indexes": [
                    models.Index(fields=["employee_id"], name="staff_profiles_employee_id_idx"),
                    models.Index(fields=["department"], name="staff_profiles_department_idx"),
                    models.Index(fields=["branch"], name="staff_profiles_branch_idx"),
                ],
            },
        ),
    ]

