"""
Payments app models: MerchantProfile, QRPayment, BillProvider, BillPayment.

Every payment results in a Transaction via post_transaction().
QRPayment and BillPayment are satellite records that enrich the Transaction
with payment-type-specific metadata.
"""
from decimal import Decimal

from django.conf import settings
from django.db import models

from .constants import MerchantStatus, QRAmountMode, QRPaymentStatus


class MerchantProfile(models.Model):
    """
    Extended profile for merchant users.
    The related user must have role=MERCHANT_CUSTOMER.
    settlement_account receives credits from QR and bill payments.
    """
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="merchant_profile",
    )
    settlement_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="merchant_settlements",
    )
    business_name = models.CharField(max_length=255)
    business_type = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=100, unique=True)
    tax_number = models.CharField(max_length=100, blank=True)
    contact_phone = models.CharField(max_length=20)
    address = models.TextField(blank=True)
    status = models.CharField(
        max_length=30,
        choices=MerchantStatus.CHOICES,
        default=MerchantStatus.ACTIVE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "merchant_profiles"
        indexes = [
            models.Index(fields=["registration_number"]),
            models.Index(fields=["status"]),
            models.Index(fields=["business_name"]),
        ]

    def __str__(self) -> str:
        return f"{self.business_name} ({self.status})"


class QRPayment(models.Model):
    """
    Represents a QR code generated by a merchant.

    Lifecycle: PENDING → PAID (on successful payment) or EXPIRED / CANCELLED.
    The transaction FK is null until a payer completes the payment.
    """
    transaction = models.OneToOneField(
        "ledger.Transaction",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="qr_payment",
    )
    merchant_profile = models.ForeignKey(
        MerchantProfile,
        on_delete=models.PROTECT,
        related_name="qr_payments",
    )
    merchant_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="qr_merchant_payments",
    )
    payer_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="qr_payer_payments",
    )
    qr_token = models.CharField(max_length=128, unique=True)
    qr_payload_hash = models.CharField(max_length=128)
    amount_mode = models.CharField(
        max_length=20,
        choices=QRAmountMode.CHOICES,
        default=QRAmountMode.FIXED,
    )
    display_amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Amount in FIXED mode. Null in OPEN mode.",
    )
    currency = models.ForeignKey(
        "accounts.Currency",
        on_delete=models.PROTECT,
        related_name="qr_payments",
        default="USD",
    )
    status = models.CharField(
        max_length=20,
        choices=QRPaymentStatus.CHOICES,
        default=QRPaymentStatus.PENDING,
    )
    scanned_at = models.DateTimeField(null=True, blank=True)
    expires_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "qr_payments"
        indexes = [
            models.Index(fields=["qr_token"]),
            models.Index(fields=["merchant_profile", "created_at"]),
            models.Index(fields=["merchant_account", "created_at"]),
            models.Index(fields=["status", "expires_at"]),
        ]

    def __str__(self) -> str:
        return f"QR {self.qr_token[:12]}… [{self.status}]"


class BillProvider(models.Model):
    """
    External bill service (electricity, water, telecom, etc.).
    provider_account receives credits when bills are paid.
    """
    code = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=255)
    service_type = models.CharField(max_length=50)
    provider_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="bill_provider_payments",
    )
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "bill_providers"
        indexes = [
            models.Index(fields=["code"]),
            models.Index(fields=["service_type", "is_active"]),
        ]

    def __str__(self) -> str:
        return f"{self.name} ({self.code})"


class BillPayment(models.Model):
    """
    Satellite record enriching a BILL_PAYMENT Transaction with biller-specific
    metadata (service number, bill reference, biller amount).
    """
    transaction = models.OneToOneField(
        "ledger.Transaction",
        on_delete=models.PROTECT,
        related_name="bill_payment",
    )
    bill_provider = models.ForeignKey(
        BillProvider,
        on_delete=models.PROTECT,
        related_name="payments",
    )
    payer_account = models.ForeignKey(
        "accounts.Account",
        on_delete=models.PROTECT,
        related_name="bill_payments",
    )
    service_number = models.CharField(max_length=100)
    bill_reference = models.CharField(max_length=100)
    biller_amount = models.DecimalField(max_digits=18, decimal_places=2)
    fee_amount = models.DecimalField(
        max_digits=18,
        decimal_places=2,
        default=Decimal("0"),
    )
    fetched_at = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "bill_payments"
        indexes = [
            models.Index(fields=["bill_provider", "service_number"]),
            models.Index(fields=["payer_account", "created_at"]),
            models.Index(fields=["bill_reference"]),
        ]

    def __str__(self) -> str:
        return (
            f"Bill {self.bill_provider.code} / {self.service_number} "
            f"— {self.biller_amount}"
        )
