# Generated by Django 6.0.4 on 2026-04-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlockevent',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_user_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountlockevent',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_user_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountlockevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_lock_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='otp_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_audits', to='security.otprequest'),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_reset_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountlockevent',
            index=models.Index(fields=['user', 'is_active'], name='account_loc_user_id_30ae34_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlockevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='account_loc_event_t_660180_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['phone_number', 'attempted_at'], name='login_logs_phone_n_e7d181_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', 'attempted_at'], name='login_logs_user_id_ebd934_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['status', 'attempted_at'], name='login_logs_status_215414_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['device_id'], name='login_logs_device__55000f_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone_number', 'created_at'], name='otp_request_phone_n_27e506_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['request_type', 'status'], name='otp_request_request_988b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['expires_at'], name='otp_request_expires_21a7df_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['purpose_reference'], name='otp_request_purpose_83704b_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetaudit',
            index=models.Index(fields=['user', 'created_at'], name='password_re_user_id_4a7828_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetaudit',
            index=models.Index(fields=['initiated_by', 'created_at'], name='password_re_initiat_f89e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetaudit',
            index=models.Index(fields=['reset_type', 'success'], name='password_re_reset_t_e5a5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_uuid'], name='user_device_device__bbc516_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_trusted'], name='user_device_user_id_bee353_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['last_seen_at'], name='user_device_last_se_e820c1_idx'),
        ),
    ]
