# Generated by Django 6.0.4 on 2026-04-21 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_currencies'),
        ('ledger', '0001_initial'),
        ('security', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('LOGIN', 'Login')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ACTIONED', 'Actioned')], db_index=True, default='OPEN', max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rules_triggered', models.JSONField(default=list)),
                ('auto_action_taken', models.CharField(blank=True, max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='accounts.account')),
                ('login_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='security.loginlog')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='ledger.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DISMISS', 'Dismiss — no action required'), ('WARN', 'Warn — monitor, no account action'), ('FREEZE_ACCOUNT', 'Freeze Account'), ('BLOCK_ACCOUNT', 'Block Account'), ('ESCALATE', 'Escalate to senior officer')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='risk.fraudalert')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_decisions',
            },
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status', 'severity'], name='fraud_alert_status_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['user', 'created_at'], name='fraud_alert_user_idx'),
        ),
    ]
