# Generated by Django 6.0.4 on 2026-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='combined_score',
            field=models.IntegerField(default=0, help_text='Hybrid score (ML + rules)'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='ml_fraud_probability',
            field=models.FloatField(blank=True, help_text='ML model fraud probability (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='rule_based_score',
            field=models.IntegerField(blank=True, help_text='Original rule-based score', null=True),
        ),
    ]
