# Generated by Django 6.0.4 on 2026-04-20 18:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=40, unique=True)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('QR_PAYMENT', 'QR Payment'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('MOBILE', 'Mobile App'), ('API', 'API'), ('STAFF', 'Staff Terminal'), ('SYSTEM', 'System')], default='MOBILE', max_length=30)),
                ('requires_otp', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.currency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to=settings.AUTH_USER_MODEL)),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='ledger.transaction')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('FEE', 'Fee'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_entries', to='accounts.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'db_table': 'transaction_entries',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=40)),
                ('transaction_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payload_json', models.JSONField(default=dict)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='ledger.transaction')),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('QR_PAYMENT', 'QR Payment'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null = no upper limit on transaction amount.', max_digits=18, null=True)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('percentage_fee', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='e.g. 0.0150 for 1.50%', max_digits=7)),
                ('min_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Null = no cap on fee amount.', max_digits=18, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower number = higher priority when multiple rules match.')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_rules', to='accounts.currency')),
            ],
            options={
                'db_table': 'fee_rules',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['transaction_type', 'currency', 'is_active'], name='fee_rules_transac_f54e09_idx'), models.Index(fields=['effective_from', 'effective_to'], name='fee_rules_effecti_e99f13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='transaction_referen_dda4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'occurred_at'], name='transaction_custome_e25a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['initiated_by', 'occurred_at'], name='transaction_initiat_3642bf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['completed_at'], name='transaction_complet_6d39d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['account', 'created_at'], name='transaction_account_793c88_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['entry_type', 'created_at'], name='transaction_entry_t_82bbd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionentry',
            unique_together={('transaction', 'sequence_no')},
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['reference_number'], name='transaction_referen_8846df_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['archived_at'], name='transaction_archive_09cc4d_idx'),
        ),
    ]
