# Generated by Django 6.0.4 on 2026-04-20 17:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'indexes': [models.Index(fields=['is_active'], name='currencies_is_acti_18a8da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('blocked_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.currency')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('FREEZE', 'Freeze'), ('BLOCK', 'Block')], max_length=20)),
                ('reason', models.TextField()),
                ('source', models.CharField(choices=[('RISK_OFFICER', 'Risk Officer'), ('ADMIN', 'Admin'), ('COMPLIANCE', 'Compliance'), ('AUTO', 'Auto')], default='RISK_OFFICER', max_length=30)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restrictions', to='accounts.account')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_restrictions', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_restrictions',
                'indexes': [models.Index(fields=['account', 'is_active'], name='account_res_account_2acc2b_idx'), models.Index(fields=['restriction_type', 'is_active'], name='account_res_restric_1ed6b4_idx'), models.Index(fields=['starts_at'], name='account_res_starts__034f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_beneficiary', to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beneficiaries',
                'indexes': [models.Index(fields=['owner', 'is_active'], name='beneficiari_owner_i_4c2c08_idx')],
                'unique_together': {('owner', 'destination_account')},
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='accounts_account_2815ed_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'status'], name='accounts_user_id_e05c06_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency', 'status'], name='accounts_currenc_ffebcf_idx'),
        ),
    ]
