# Generated by Django 6.0.4 on 2026-04-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KycProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legal_full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("id_type", models.CharField(choices=[("NATIONAL_ID", "National ID"), ("PASSPORT", "Passport"), ("RESIDENCE_PERMIT", "Residence Permit")], max_length=50)),
                ("id_number", models.CharField(max_length=100)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_city", models.CharField(max_length=120)),
                ("address_country", models.CharField(max_length=120)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="kyc_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "kyc_profiles",
                "indexes": [
                    models.Index(fields=["user"], name="kyc_profile_user_idx"),
                    models.Index(fields=["submitted_at"], name="kyc_profile_submitted_at_idx"),
                ],
            },
        ),
    ]

