# Generated by Django 6.0.4 on 2026-04-20 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_currencies'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_provider_payments', to='accounts.account')),
            ],
            options={
                'db_table': 'bill_providers',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=100)),
                ('bill_reference', models.CharField(max_length=100)),
                ('biller_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='accounts.account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payment', to='ledger.transaction')),
                ('bill_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.billprovider')),
            ],
            options={
                'db_table': 'bill_payments',
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_settlements', to='accounts.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchant_profiles',
            },
        ),
        migrations.CreateModel(
            name='QRPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=128, unique=True)),
                ('qr_payload_hash', models.CharField(max_length=128)),
                ('amount_mode', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('OPEN', 'Open Amount')], default='FIXED', max_length=20)),
                ('display_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in FIXED mode. Null in OPEN mode.', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(default='SAR', on_delete=django.db.models.deletion.PROTECT, related_name='qr_payments', to='accounts.currency')),
                ('merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_merchant_payments', to='accounts.account')),
                ('merchant_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_payments', to='payments.merchantprofile')),
                ('payer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_payer_payments', to='accounts.account')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qr_payment', to='ledger.transaction')),
            ],
            options={
                'db_table': 'qr_payments',
            },
        ),
        migrations.AddIndex(
            model_name='billprovider',
            index=models.Index(fields=['code'], name='bill_provid_code_884523_idx'),
        ),
        migrations.AddIndex(
            model_name='billprovider',
            index=models.Index(fields=['service_type', 'is_active'], name='bill_provid_service_220066_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['bill_provider', 'service_number'], name='bill_paymen_bill_pr_69b7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['payer_account', 'created_at'], name='bill_paymen_payer_a_f2bd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['bill_reference'], name='bill_paymen_bill_re_8476fd_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['registration_number'], name='merchant_pr_registr_43fcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['status'], name='merchant_pr_status_90e6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantprofile',
            index=models.Index(fields=['business_name'], name='merchant_pr_busines_cd27fa_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpayment',
            index=models.Index(fields=['qr_token'], name='qr_payments_qr_toke_5d02b3_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpayment',
            index=models.Index(fields=['merchant_profile', 'created_at'], name='qr_payments_merchan_ac1de0_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpayment',
            index=models.Index(fields=['merchant_account', 'created_at'], name='qr_payments_merchan_ceb745_idx'),
        ),
        migrations.AddIndex(
            model_name='qrpayment',
            index=models.Index(fields=['status', 'expires_at'], name='qr_payments_status_6f35ca_idx'),
        ),
    ]
